In [2]:
import os
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 'Files Excercises.ipynb',
 'Pandas',
 'Python Mega Course.iml',
 'python_basics',
 'SQL DB Project',
 'Testing.ipynb',
 'Thesaursus Project']

In [3]:
import pandas

In [4]:
df1=pandas.read_csv("C:\\Users\\spilcher\\OneDrive - Schlumberger\\Documents\\jupyter files\\supermarkets.csv")
df1

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [5]:
df2=pandas.read_json("C:\\Users\\spilcher\\OneDrive - Schlumberger\\Documents\\jupyter files\\supermarkets.json")
df2

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [4]:
import pandas
df3=pandas.read_excel("C:\\Users\\spilcher\\OneDrive - Schlumberger\\Documents\\jupyter files\\supermarkets.xlsx", sheet_name=0)
df3

,ID,Address,City,State,Country,Supermarket Name,Number of Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [6]:
df4=pandas.read_csv("C:\\Users\\spilcher\\OneDrive - Schlumberger\\Documents\\jupyter files\\supermarkets-commas.txt")
df4

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [14]:
df5=pandas.read_csv("C:\\Users\\spilcher\\OneDrive - Schlumberger\\Documents\\jupyter files\\supermarkets-semi-colons.txt", sep=';')
df5

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [18]:
df5.loc[0:4, 'State':'Name']

              State Country          Name
0          CA 94114     USA       Madeira
1          CA 94119     USA   Bready Shop
2  California 94114     USA   Super River
3          CA 94114     USA    Ben's Shop
4        California     USA       Sanchez

In [19]:
df5.iloc[3:5, 1:3]

           Address           City
3     3995 23rd St  San Francisco
4  1056 Sanchez St  San Francisco

In [21]:
df5.drop('City', 1)

C:\Users\spilcher\AppData\Local\Temp/ipykernel_37004/1868395098.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df5.drop('City', 1)

   ID          Address             State Country          Name  Employees
0   1     3666 21st St          CA 94114     USA       Madeira          8
1   2   735 Dolores St          CA 94119     USA   Bready Shop         15
2   3      332 Hill St  California 94114     USA   Super River         25
3   4     3995 23rd St          CA 94114     USA    Ben's Shop         10
4   5  1056 Sanchez St        California     USA       Sanchez         12
5   6  551 Alvarado St          CA 94114     USA    Richvalley         20

In [22]:
df5.index

RangeIndex(start=0, stop=6, step=1)

In [26]:
df5['Continent']=df5.shape[0]*['North America']
df5

,ID,Address,City,State,Country,Name,Employees,Continent
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,North America
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,North America
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,North America
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,North America
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,North America
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,North America

In [27]:
import geopy
dir(geopy)

['AlgoliaPlaces',
 'ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'Geocodio',
 'Geolake',
 'GoogleV3',
 'Here',
 'HereV7',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'What3WordsV3',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [36]:
    from geopy.geocoders import ArcGIS

In [38]:
nom = ArcGIS()

In [39]:
n=nom.geocode("3995 23rd St,San Francisco,CA 94114,USA")

GeocoderUnavailable: HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Max retries exceeded with url: /arcgis/rest/services/World/GeocodeServer/findAddressCandidates?singleLine=3995+23rd+St%2CSan+Francisco%2CCA+94114%2CUSA&f=json&maxLocations=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='geocode.arcgis.com', port=443): Read timed out. (read timeout=1)"))